# Tomcat settings
server:
    port: 8080
    context-path: /
    compression:
        enabled: true
    tomcat:
        uri-encoding: UTF-8

# Spring settings
spring:
    profiles:
        active: dev

# Project settings
project:
    java-home: ${JAVA_HOME}
    kotlin-home: ${KOTLIN_HOME:Find nothing!!!}-Append Static Remark.
