# Tomcat settings
server:
    port: 8080
    context-path: /
    compression:
        enabled: true
    tomcat:
        uri-encoding: UTF-8

# Spring settings
spring:
    profiles:
        active: dev
    messages:
        basename: i18n/tips
        cache-duration: 86400
        encoding: UTF-8

# Project settings
project:
    java-home: ${JAVA_HOME}
    kotlin-home: ${KOTLIN_HOME:Find nothing!!!}-Append Static Remark.
